### ISSUE TITLE
CognitiveBingNews doesn't work

### ISSUE THREAD

**Issue by jamintz** [aggounix/cognitivebing#2]
CognitiveBing is fine, uninitialized constant for CognitiveBingNews. Why isn't it wrapped into the same places as images / video?

**Comment by aggounix** [comment]
Hi, I wanted to make a seperate class for news to have different methode (search, trending....)
I will try to fix thix bug
thx for signaling it

**Comment by aggounix** [comment]
Fixed!
Please download 0.2.1 version

**Comment by jamintz** [comment]
Great thanks
